version: '3.8'

services:
  trading-bot:
    build: .
    container_name: live-trading-bot
    volumes:
      - ./.env:/app/.env
      - ./logs/:/app/logs/
      - ./:/app/
    environment:
      - TZ=UTC
    restart: unless-stopped